/*********************************************************
 * Do not edit this file. It has been auto generated by  *
 * ../extmethods/blas/gen_clblas.py at ${timestamp}. *
 *********************************************************/
#include <bh_extmethod.hpp>
#include "../ve/opencl/engine_opencl.hpp"

#include <clBLAS.h>

#include <stdio.h>
#include <map>

using namespace bohrium;
using namespace extmethod;
using namespace std;

namespace {
    ${body}
} /* end of namespace */

${footer}
