/**********************************************************
 * Do not edit this file. It has been auto generated by   *
 * ../core/codegen/gen_extmethod.py at ${timestamp}.  *
 **********************************************************/
#include <bh_extmethod.hpp>

#if defined(__APPLE__) || defined(__MACOSX)
    #include <Accelerate/Accelerate.h>
#else
    #include <cblas.h>
#endif

#include <stdexcept>

using namespace bohrium;
using namespace extmethod;
using namespace std;

namespace {
    ${body}
} /* end of namespace */

${footer}
