/**********************************************************
 * Do not edit this file. It has been auto generated by   *
 * ../core/codegen/gen_extmethod.py at @!timestamp!@.  *
 **********************************************************/
#include <bohrium/bh_extmethod.hpp>
#include <bohrium/bh_pprint.hpp>
#include <bohrium/bh_main_memory.hpp>

#include "opencv2/imgproc/imgproc.hpp"

using namespace bohrium;
using namespace extmethod;
using namespace std;

namespace {
    @!body!@
} /* end of namespace */

@!footer!@
