FROM ubuntu:14.04
MAINTAINER Mads R. B. Kristensen <madsbk@gmail.com>
RUN apt-get update
RUN apt-get install -y wget unzip
RUN apt-get install -y cmake swig python python-numpy python-cheetah python-dev fftw3-dev cython ocl-icd-opencl-dev libboost-serialization-dev libboost-system-dev libboost-filesystem-dev libboost-thread-dev mono-devel mono-gmcs libhwloc-dev freeglut3-dev libxmu-dev libxi-dev fglrx fglrx-dev opencl-headers
