/*
 * Copyright 2011 Troels Blum <troels@blum.dk>
 *
 * This file is part of cphVB.
 *
 * cphVB is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * cphVB is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with cphVB.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "CUDAerrorCode.h"

const char* _cudaErrorStr [] =
{
    [CUDA_SUCCESS] = "CUDA_SUCCESS",
    [CUDA_ERROR_INVALID_VALUE] = "CUDA_ERROR_INVALID_VALUE",
    [CUDA_ERROR_OUT_OF_MEMORY] = "CUDA_ERROR_OUT_OF_MEMORY",
    [CUDA_ERROR_NOT_INITIALIZED] = "CUDA_ERROR_NOT_INITIALIZED",
    [CUDA_ERROR_DEINITIALIZED] = "CUDA_ERROR_DEINITIALIZED",
    [CUDA_ERROR_NO_DEVICE] = "CUDA_ERROR_NO_DEVICE",
    [CUDA_ERROR_INVALID_DEVICE] = "CUDA_ERROR_INVALID_DEVICE",
    [CUDA_ERROR_INVALID_IMAGE] = "CUDA_ERROR_INVALID_IMAGE",
    [CUDA_ERROR_INVALID_CONTEXT] = "CUDA_ERROR_INVALID_CONTEXT",
    [CUDA_ERROR_CONTEXT_ALREADY_CURRENT] = "CUDA_ERROR_CONTEXT_ALREADY_CURRENT",
    [CUDA_ERROR_MAP_FAILED] = "CUDA_ERROR_MAP_FAILED",
    [CUDA_ERROR_UNMAP_FAILED] = "CUDA_ERROR_UNMAP_FAILED",
    [CUDA_ERROR_ARRAY_IS_MAPPED] = "CUDA_ERROR_ARRAY_IS_MAPPED",
    [CUDA_ERROR_ALREADY_MAPPED] = "CUDA_ERROR_ALREADY_MAPPED",
    [CUDA_ERROR_NO_BINARY_FOR_GPU] = "CUDA_ERROR_NO_BINARY_FOR_GPU",
    [CUDA_ERROR_ALREADY_ACQUIRED] = "CUDA_ERROR_ALREADY_ACQUIRED",
    [CUDA_ERROR_NOT_MAPPED] = "CUDA_ERROR_NOT_MAPPED",
    [CUDA_ERROR_NOT_MAPPED_AS_ARRAY] = "CUDA_ERROR_NOT_MAPPED_AS_ARRAY",
    [CUDA_ERROR_NOT_MAPPED_AS_POINTER] = "CUDA_ERROR_NOT_MAPPED_AS_POINTER",
    [CUDA_ERROR_ECC_UNCORRECTABLE] = "CUDA_ERROR_ECC_UNCORRECTABLE",
    [CUDA_ERROR_UNSUPPORTED_LIMIT] = "CUDA_ERROR_UNSUPPORTED_LIMIT",
    [CUDA_ERROR_INVALID_SOURCE] = "CUDA_ERROR_INVALID_SOURCE",
    [CUDA_ERROR_FILE_NOT_FOUND] = "CUDA_ERROR_FILE_NOT_FOUND",
    [CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND] = "CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND",
    [CUDA_ERROR_SHARED_OBJECT_INIT_FAILED] = "CUDA_ERROR_SHARED_OBJECT_INIT_FAILED",
    [CUDA_ERROR_OPERATING_SYSTEM] = "CUDA_ERROR_OPERATING_SYSTEM",
    [CUDA_ERROR_INVALID_HANDLE] = "CUDA_ERROR_INVALID_HANDLE",
    [CUDA_ERROR_NOT_FOUND] = "CUDA_ERROR_NOT_FOUND",
    [CUDA_ERROR_NOT_READY] = "CUDA_ERROR_NOT_READY",
    [CUDA_ERROR_LAUNCH_FAILED] = "CUDA_ERROR_LAUNCH_FAILED",
    [CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES] = "CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES",
    [CUDA_ERROR_LAUNCH_TIMEOUT] = "CUDA_ERROR_LAUNCH_TIMEOUT",
    [CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING] = "CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING",
    [CUDA_ERROR_UNKNOWN] = "CUDA_ERROR_UNKNOWN"
};
    
const char* cudaErrorStr(CUresult ec)
{
    return _cudaErrorStr[ec];
}
