#!/usr/bin/env bash

DOCDIR="/tmp/cphvbdocs"

if [ -d "$DOCDIR" ]; then
    # Do nothing...
    echo "Already got repos, not cloning."
else
    # Grab the repos
    git clone git@bitbucket.org:cphvb/cphvb.bitbucket.org.git $DOCDIR
fi

# Generate C++ docs
doxygen Doxyfile

# Generate HTML from sphinx
make html

# Copy to repos
cp -r build/html/* $DOCDIR
cd $DOCDIR
git add .
git commit -a -m "Autogenerated docs."
git push

