#ifndef __CPHVB_ERROR_H
#define __CPHVB_ERROR_H

/* Error codes */
typedef enum
{
    CPHVB_SUCCESS,
    CPHVB_ERROR,
    CPHVB_INST_ERROR,
    CPHVB_INST_NOT_SUPPORTED,
    CPHVB_INST_NOT_SUPPORTED_FOR_SLICE,
    CPHVB_TYPE_ERROR,
    CPHVB_TYPE_NOT_SUPPORTED,
    CPHVB_TYPE_NOT_SUPPORTED_BY_OP,
    CPHVB_TYPE_COMBINATION_NOT_SUPPORTED,
    CPHVB_OUT_OF_MEMORY,
    CPHVB_RESULT_IS_CONSTANT,
    CPHVB_OPERAND_UNKNOWN
} cphvb_error ;

#endif
