#!/usr/bin/env python
import traceback
import argparse
import genesis
import pprint
import sys

import bhutils
import layout

if __name__ == "__main__":

    p = argparse.ArgumentParser(description='A bunch of Bohrium related stuff...')
    p.add_argument(
        '--config',
        help='Path to Bohrium config-file.'
    )
    p.add_argument(
        '--genesis',
        help='Run the bytecode genesis-program.',
        action='store_true'
    )
    p.add_argument(
        '--mangle',
        help='Modify the bytecode in some way...',
        action='store_true'
    )
    p.add_argument(
        '--merge_kernels',
        help='Compile all kernels in cpu(kernel-path) into a shared library.',
        action='store_true'
    )
    p.add_argument(
        'bohrium',
        help='Path to Bohrium source-code.'
    )
    args = p.parse_args()

    config = bhutils.load_config(args.config)
    opcodes, types = bhutils.load_bytecode(args.bohrium)

    out, err = (None, None)
    if args.genesis:
        out, err = genesis.genesis(opcodes, types)
    if args.merge_kernels:
        out, err = cpu.merge_kernels(config)
    if args.mangle:
        out, err = layout.mangle(opcodes, types)

